import type { Order } from "./types";

const now = Date.now();
const m = (mins: number) => new Date(now - mins * 60_000).toISOString();

export const initialMockOrders: Order[] = [
  {
    id: "o1",
    orderNumber: "A1B2",
    status: "PENDING",
    customerName: "Sarah Mitchell",
    customerPhone: "+1 415 555 0142",
    customerAddress: "1420 Folsom St, Apt 3B, San Francisco, CA 94103",
    customerNotes: "Please ring buzzer twice. Allergic to nuts.",
    subtotal: 3450,
    deliveryFee: 499,
    total: 3949,
    declineReason: null,
    customerNotified: false,
    placedAt: m(2),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i1", menuItemId: "m1", nameSnapshot: "Margherita Pizza", priceSnapshot: 1450, quantity: 1, notes: "Extra basil" },
      { id: "i2", menuItemId: "m2", nameSnapshot: "Caesar Salad", priceSnapshot: 1000, quantity: 2, notes: null },
    ],
  },
  {
    id: "o2",
    orderNumber: "C3D4",
    status: "PENDING",
    customerName: "Marcus Chen",
    customerPhone: "+1 415 555 0188",
    customerAddress: "88 Market St, San Francisco, CA 94105",
    customerNotes: null,
    subtotal: 2295,
    deliveryFee: 499,
    total: 2794,
    declineReason: null,
    customerNotified: false,
    placedAt: m(5),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i3", menuItemId: "m3", nameSnapshot: "Classic Cheeseburger", priceSnapshot: 1295, quantity: 1, notes: "No pickles" },
      { id: "i4", menuItemId: "m4", nameSnapshot: "Truffle Fries", priceSnapshot: 800, quantity: 1, notes: null },
      { id: "i5", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 200, quantity: 1, notes: null },
    ],
  },
  {
    id: "o3",
    orderNumber: "E5F6",
    status: "PENDING",
    customerName: "Priya Patel",
    customerPhone: "+1 415 555 0199",
    customerAddress: "501 Mission St, Suite 12, San Francisco, CA 94105",
    customerNotes: "Leave at door. Contactless please.",
    subtotal: 4180,
    deliveryFee: 499,
    total: 4679,
    declineReason: null,
    customerNotified: false,
    placedAt: m(7),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i6", menuItemId: "m6", nameSnapshot: "Pepperoni Pizza", priceSnapshot: 1690, quantity: 1, notes: null },
      { id: "i7", menuItemId: "m7", nameSnapshot: "Spaghetti Carbonara", priceSnapshot: 1690, quantity: 1, notes: "Extra pancetta" },
      { id: "i8", menuItemId: "m8", nameSnapshot: "Tiramisu", priceSnapshot: 800, quantity: 1, notes: null },
    ],
  },
  {
    id: "o4",
    orderNumber: "G7H8",
    status: "ACCEPTED",
    customerName: "Daniel Kim",
    customerPhone: "+1 415 555 0211",
    customerAddress: "240 Valencia St, San Francisco, CA 94103",
    customerNotes: null,
    subtotal: 1850,
    deliveryFee: 499,
    total: 2349,
    declineReason: null,
    customerNotified: true,
    placedAt: m(11),
    acceptedAt: m(9),
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i9", menuItemId: "m9", nameSnapshot: "BBQ Bacon Burger", priceSnapshot: 1550, quantity: 1, notes: null },
      { id: "i10", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 300, quantity: 1, notes: null },
    ],
  },
  {
    id: "o5",
    orderNumber: "J9K0",
    status: "IN_PROGRESS",
    customerName: "Olivia Rodriguez",
    customerPhone: "+1 415 555 0234",
    customerAddress: "1199 Bush St, San Francisco, CA 94109",
    customerNotes: "Gluten-free if possible.",
    subtotal: 3290,
    deliveryFee: 499,
    total: 3789,
    declineReason: null,
    customerNotified: true,
    placedAt: m(18),
    acceptedAt: m(16),
    startedAt: m(12),
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i11", menuItemId: "m10", nameSnapshot: "Quattro Formaggi Pizza", priceSnapshot: 1790, quantity: 1, notes: null },
      { id: "i12", menuItemId: "m11", nameSnapshot: "Penne Arrabbiata", priceSnapshot: 1500, quantity: 1, notes: "Extra spicy" },
    ],
  },
  {
    id: "o6",
    orderNumber: "L1M2",
    status: "IN_PROGRESS",
    customerName: "James Thompson",
    customerPhone: "+1 415 555 0256",
    customerAddress: "350 Bay St, San Francisco, CA 94133",
    customerNotes: null,
    subtotal: 2640,
    deliveryFee: 499,
    total: 3139,
    declineReason: null,
    customerNotified: true,
    placedAt: m(22),
    acceptedAt: m(20),
    startedAt: m(15),
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i13", menuItemId: "m12", nameSnapshot: "Mushroom Risotto", priceSnapshot: 1640, quantity: 1, notes: null },
      { id: "i14", menuItemId: "m2", nameSnapshot: "Caesar Salad", priceSnapshot: 1000, quantity: 1, notes: null },
    ],
  },
  {
    id: "o7",
    orderNumber: "N3P4",
    status: "READY",
    customerName: "Aisha Williams",
    customerPhone: "+1 415 555 0278",
    customerAddress: "1500 Howard St, San Francisco, CA 94103",
    customerNotes: "Pickup at 7pm.",
    subtotal: 1995,
    deliveryFee: 0,
    total: 1995,
    declineReason: null,
    customerNotified: true,
    placedAt: m(28),
    acceptedAt: m(26),
    startedAt: m(22),
    readyAt: m(2),
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i15", menuItemId: "m13", nameSnapshot: "Hawaiian Pizza", priceSnapshot: 1495, quantity: 1, notes: null },
      { id: "i16", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 250, quantity: 2, notes: null },
    ],
  },
  {
    id: "o8",
    orderNumber: "Q5R6",
    status: "READY",
    customerName: "Ethan Brooks",
    customerPhone: "+1 415 555 0290",
    customerAddress: "77 Geary St, San Francisco, CA 94108",
    customerNotes: null,
    subtotal: 4290,
    deliveryFee: 499,
    total: 4789,
    declineReason: null,
    customerNotified: true,
    placedAt: m(31),
    acceptedAt: m(29),
    startedAt: m(25),
    readyAt: m(4),
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i17", menuItemId: "m1", nameSnapshot: "Margherita Pizza", priceSnapshot: 1450, quantity: 2, notes: null },
      { id: "i18", menuItemId: "m11", nameSnapshot: "Penne Arrabbiata", priceSnapshot: 1390, quantity: 1, notes: null },
    ],
  },
];
