import type { Order } from "./types";

const now = Date.now();
const m = (mins: number) => new Date(now - mins * 60_000).toISOString();

export const initialMockOrders: Order[] = [
  {
    id: "o1",
    orderNumber: "A1B2",
    trackingToken: "trk_a1b2_o1",
    cancelToken: "cnl_a1b2_o1",
    status: "PENDING",
    customerName: "Sarah Mitchell",
    customerPhone: "+1 415 555 0142",
    customerAddress: "1420 Folsom St, Apt 3B, San Francisco, CA 94103",
    customerNotes: "Please ring buzzer twice. Allergic to nuts.",
    subtotal: 3450,
    deliveryFee: 499,
    total: 3949,
    declineReason: null,
    customerNotified: false,
    placedAt: m(2),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i1", menuItemId: "m1", nameSnapshot: "Margherita Pizza", priceSnapshot: 1450, quantity: 1, notes: "Extra basil" },
      { id: "i2", menuItemId: "m2", nameSnapshot: "Caesar Salad", priceSnapshot: 1000, quantity: 2, notes: null },
    ],
  },
  {
    id: "o2",
    orderNumber: "C3D4",
    trackingToken: "trk_c3d4_o2",
    cancelToken: "cnl_c3d4_o2",
    status: "PENDING",
    customerName: "Marcus Chen",
    customerPhone: "+1 415 555 0188",
    customerAddress: "88 Market St, San Francisco, CA 94105",
    customerNotes: null,
    subtotal: 2295,
    deliveryFee: 499,
    total: 2794,
    declineReason: null,
    customerNotified: false,
    placedAt: m(5),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i3", menuItemId: "m3", nameSnapshot: "Classic Cheeseburger", priceSnapshot: 1295, quantity: 1, notes: "No pickles" },
      { id: "i4", menuItemId: "m4", nameSnapshot: "Truffle Fries", priceSnapshot: 800, quantity: 1, notes: null },
      { id: "i5", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 200, quantity: 1, notes: null },
    ],
  },
  {
    id: "o3",
    orderNumber: "E5F6",
    trackingToken: "trk_e5f6_o3",
    cancelToken: "cnl_e5f6_o3",
    status: "PENDING",
    customerName: "Priya Patel",
    customerPhone: "+1 415 555 0199",
    customerAddress: "501 Mission St, Suite 12, San Francisco, CA 94105",
    customerNotes: "Leave at door. Contactless please.",
    subtotal: 4180,
    deliveryFee: 499,
    total: 4679,
    declineReason: null,
    customerNotified: false,
    placedAt: m(7),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i6", menuItemId: "m6", nameSnapshot: "Pepperoni Pizza", priceSnapshot: 1690, quantity: 1, notes: null },
      { id: "i7", menuItemId: "m7", nameSnapshot: "Spaghetti Carbonara", priceSnapshot: 1690, quantity: 1, notes: "Extra pancetta" },
      { id: "i8", menuItemId: "m8", nameSnapshot: "Tiramisu", priceSnapshot: 800, quantity: 1, notes: null },
    ],
  },
  {
    id: "o4",
    orderNumber: "G7H8",
    trackingToken: "trk_g7h8_o4",
    cancelToken: "cnl_g7h8_o4",
    status: "ACCEPTED",
    customerName: "Daniel Kim",
    customerPhone: "+1 415 555 0211",
    customerAddress: "240 Valencia St, San Francisco, CA 94103",
    customerNotes: null,
    subtotal: 1850,
    deliveryFee: 499,
    total: 2349,
    declineReason: null,
    customerNotified: true,
    placedAt: m(11),
    acceptedAt: m(9),
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i9", menuItemId: "m9", nameSnapshot: "BBQ Bacon Burger", priceSnapshot: 1550, quantity: 1, notes: null },
      { id: "i10", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 300, quantity: 1, notes: null },
    ],
  },
  {
    id: "o5",
    orderNumber: "J9K0",
    trackingToken: "trk_j9k0_o5",
    cancelToken: "cnl_j9k0_o5",
    status: "IN_PROGRESS",
    customerName: "Olivia Rodriguez",
    customerPhone: "+1 415 555 0234",
    customerAddress: "1199 Bush St, San Francisco, CA 94109",
    customerNotes: "Gluten-free if possible.",
    subtotal: 3290,
    deliveryFee: 499,
    total: 3789,
    declineReason: null,
    customerNotified: true,
    placedAt: m(18),
    acceptedAt: m(16),
    startedAt: m(12),
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i11", menuItemId: "m10", nameSnapshot: "Quattro Formaggi Pizza", priceSnapshot: 1790, quantity: 1, notes: null },
      { id: "i12", menuItemId: "m11", nameSnapshot: "Penne Arrabbiata", priceSnapshot: 1500, quantity: 1, notes: "Extra spicy" },
    ],
  },
  {
    id: "o6",
    orderNumber: "L1M2",
    trackingToken: "trk_l1m2_o6",
    cancelToken: "cnl_l1m2_o6",
    status: "IN_PROGRESS",
    customerName: "James Thompson",
    customerPhone: "+1 415 555 0256",
    customerAddress: "350 Bay St, San Francisco, CA 94133",
    customerNotes: null,
    subtotal: 2640,
    deliveryFee: 499,
    total: 3139,
    declineReason: null,
    customerNotified: true,
    placedAt: m(22),
    acceptedAt: m(20),
    startedAt: m(15),
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i13", menuItemId: "m12", nameSnapshot: "Mushroom Risotto", priceSnapshot: 1640, quantity: 1, notes: null },
      { id: "i14", menuItemId: "m2", nameSnapshot: "Caesar Salad", priceSnapshot: 1000, quantity: 1, notes: null },
    ],
  },
  {
    id: "o7",
    orderNumber: "N3P4",
    trackingToken: "trk_n3p4_o7",
    cancelToken: "cnl_n3p4_o7",
    status: "READY",
    customerName: "Aisha Williams",
    customerPhone: "+1 415 555 0278",
    customerAddress: "1500 Howard St, San Francisco, CA 94103",
    customerNotes: "Pickup at 7pm.",
    subtotal: 1995,
    deliveryFee: 0,
    total: 1995,
    declineReason: null,
    customerNotified: true,
    placedAt: m(28),
    acceptedAt: m(26),
    startedAt: m(22),
    readyAt: m(2),
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i15", menuItemId: "m13", nameSnapshot: "Hawaiian Pizza", priceSnapshot: 1495, quantity: 1, notes: null },
      { id: "i16", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 250, quantity: 2, notes: null },
    ],
  },
  {
    id: "o8",
    orderNumber: "Q5R6",
    trackingToken: "trk_q5r6_o8",
    cancelToken: "cnl_q5r6_o8",
    status: "READY",
    customerName: "Ethan Brooks",
    customerPhone: "+1 415 555 0290",
    customerAddress: "77 Geary St, San Francisco, CA 94108",
    customerNotes: null,
    subtotal: 4290,
    deliveryFee: 499,
    total: 4789,
    declineReason: null,
    customerNotified: true,
    placedAt: m(31),
    acceptedAt: m(29),
    startedAt: m(25),
    readyAt: m(4),
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i17", menuItemId: "m1", nameSnapshot: "Margherita Pizza", priceSnapshot: 1450, quantity: 2, notes: null },
      { id: "i18", menuItemId: "m11", nameSnapshot: "Penne Arrabbiata", priceSnapshot: 1390, quantity: 1, notes: null },
    ],
  },
  {
    id: "o9",
    orderNumber: "S7T8",
    trackingToken: "trk_s7t8_o9",
    cancelToken: "cnl_s7t8_o9",
    status: "OUT_FOR_DELIVERY",
    customerName: "Hannah Lee",
    customerPhone: "+1 415 555 0312",
    customerAddress: "900 Larkin St, San Francisco, CA 94109",
    customerNotes: null,
    subtotal: 2150,
    deliveryFee: 499,
    total: 2649,
    declineReason: null,
    customerNotified: true,
    placedAt: m(45),
    acceptedAt: m(43),
    startedAt: m(40),
    readyAt: m(15),
    outForDeliveryAt: m(8),
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i19", menuItemId: "m14", nameSnapshot: "Veggie Burger", priceSnapshot: 1350, quantity: 1, notes: null },
      { id: "i20", menuItemId: "m4", nameSnapshot: "Truffle Fries", priceSnapshot: 800, quantity: 1, notes: null },
    ],
  },
  {
    id: "o10",
    orderNumber: "U9V0",
    trackingToken: "trk_u9v0_o10",
    cancelToken: "cnl_u9v0_o10",
    status: "OUT_FOR_DELIVERY",
    customerName: "Robert Garcia",
    customerPhone: "+1 415 555 0334",
    customerAddress: "2100 Lombard St, San Francisco, CA 94123",
    customerNotes: "Building entrance on side street.",
    subtotal: 3580,
    deliveryFee: 499,
    total: 4079,
    declineReason: null,
    customerNotified: true,
    placedAt: m(52),
    acceptedAt: m(50),
    startedAt: m(46),
    readyAt: m(20),
    outForDeliveryAt: m(12),
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i21", menuItemId: "m6", nameSnapshot: "Pepperoni Pizza", priceSnapshot: 1690, quantity: 1, notes: null },
      { id: "i22", menuItemId: "m15", nameSnapshot: "Buffalo Wings", priceSnapshot: 1390, quantity: 1, notes: "Extra ranch" },
      { id: "i23", menuItemId: "m5", nameSnapshot: "Coke", priceSnapshot: 250, quantity: 2, notes: null },
    ],
  },
  {
    id: "o11",
    orderNumber: "W1X2",
    trackingToken: "trk_w1x2_o11",
    cancelToken: "cnl_w1x2_o11",
    status: "DELIVERED",
    customerName: "Sophia Anderson",
    customerPhone: "+1 415 555 0356",
    customerAddress: "650 California St, San Francisco, CA 94108",
    customerNotes: null,
    subtotal: 2890,
    deliveryFee: 499,
    total: 3389,
    declineReason: null,
    customerNotified: true,
    placedAt: m(95),
    acceptedAt: m(93),
    startedAt: m(89),
    readyAt: m(65),
    outForDeliveryAt: m(55),
    deliveredAt: m(35),
    cancelledAt: null,
    declinedAt: null,
    items: [
      { id: "i24", menuItemId: "m16", nameSnapshot: "Lasagna Bolognese", priceSnapshot: 1890, quantity: 1, notes: null },
      { id: "i25", menuItemId: "m2", nameSnapshot: "Caesar Salad", priceSnapshot: 1000, quantity: 1, notes: null },
    ],
  },
  {
    id: "o12",
    orderNumber: "Y3Z4",
    trackingToken: "trk_y3z4_o12",
    cancelToken: "cnl_y3z4_o12",
    status: "DECLINED",
    customerName: "Liam Foster",
    customerPhone: "+1 415 555 0378",
    customerAddress: "12 Geary Blvd, San Francisco, CA 94118",
    customerNotes: null,
    subtotal: 1990,
    deliveryFee: 499,
    total: 2489,
    declineReason: "Out of stock",
    customerNotified: true,
    placedAt: m(120),
    acceptedAt: null,
    startedAt: null,
    readyAt: null,
    outForDeliveryAt: null,
    deliveredAt: null,
    cancelledAt: null,
    declinedAt: m(118),
    items: [
      { id: "i26", menuItemId: "m17", nameSnapshot: "Seafood Linguine", priceSnapshot: 1990, quantity: 1, notes: null },
    ],
  },
];

