/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAcceptanceRouteImport } from './routes/_authenticated/acceptance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcceptanceRoute = AuthenticatedAcceptanceRouteImport.update({
  id: '/acceptance',
  path: '/acceptance',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acceptance': typeof AuthenticatedAcceptanceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/acceptance': typeof AuthenticatedAcceptanceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/acceptance': typeof AuthenticatedAcceptanceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/acceptance' | '/admin' | '/driver' | '/kitchen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/acceptance' | '/admin' | '/driver' | '/kitchen'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/acceptance'
    | '/_authenticated/admin'
    | '/_authenticated/driver'
    | '/_authenticated/kitchen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acceptance': {
      id: '/_authenticated/acceptance'
      path: '/acceptance'
      fullPath: '/acceptance'
      preLoaderRoute: typeof AuthenticatedAcceptanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcceptanceRoute: typeof AuthenticatedAcceptanceRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcceptanceRoute: AuthenticatedAcceptanceRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
